# Site settings
title: Agi'Lille 2020
email: info@nord-agile.org
description: > # this means to ignore newlines until "baseurl:"
  L'édition de AgiLille à Lille réunira des conférences de qualité dans un cadre unique.
gems:
  - jekyll-sitemap

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://2019.agiletour-lille.org'
twitter_username: NordAgile
github_username:  jak78

# Build settings
markdown: kramdown
